
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GInterface;

import PokemonAluminum.ItemData;
import PokemonAluminum.Personagem;
import PokemonAluminum.PokeData;
import PokemonAluminum.Pokemon;
import java.awt.Color;
import static javax.swing.BorderFactory.createRaisedBevelBorder;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.INFORMATION_MESSAGE;
import javax.swing.border.Border;

/**
 *
 * @author Igor
 */
public class Choose extends javax.swing.JFrame {

    Pokemon s;
    PokeData data = new PokeData();
    Border border;
    Personagem p;
    /**
     * Creates new form Choose
     */
    public Choose() {
        border = createRaisedBevelBorder();
        p=new Personagem();
        initComponents();
        bulbabutton.setIcon(new ImageIcon(System.getProperty("user.dir")+"\\src\\icons\\pokegif\\1.gif"));
        charbutton.setIcon(new ImageIcon(System.getProperty("user.dir")+"\\src\\icons\\pokegif\\4.gif"));
        sqbutton.setIcon(new ImageIcon(System.getProperty("user.dir")+"\\src\\icons\\pokegif\\7.gif"));
        boybutton.setIcon(new ImageIcon(System.getProperty("user.dir")+"\\src\\icons\\trainers\\b.png"));
        girlbutton.setIcon(new ImageIcon(System.getProperty("user.dir")+"\\src\\icons\\trainers\\g.png"));
        JOptionPane.showMessageDialog(this, "                                       Bem vindo ao Pokemon Aluminum! \nSua jornada começa agora! Selecione a seguir o seu pokemon inicial", "Laboratório do Professor Carvalho", INFORMATION_MESSAGE, new ImageIcon(System.getProperty("user.dir")+"\\src\\icons\\mugshot\\oak.png",""));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        bulbabutton = new javax.swing.JRadioButton();
        charbutton = new javax.swing.JRadioButton();
        sqbutton = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        boybutton = new javax.swing.JRadioButton();
        girlbutton = new javax.swing.JRadioButton();
        nickTextField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup1.add(bulbabutton);
        bulbabutton.setSelected(true);
        bulbabutton.setText("Bulbassauro");
        bulbabutton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        bulbabutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bulbabuttonMouseClicked(evt);
            }
        });
        getContentPane().add(bulbabutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        buttonGroup1.add(charbutton);
        charbutton.setText("Charmander");
        charbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                charbuttonMouseClicked(evt);
            }
        });
        charbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                charbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(charbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, -1, -1));

        buttonGroup1.add(sqbutton);
        sqbutton.setText("Squirtle");
        sqbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sqbuttonMouseClicked(evt);
            }
        });
        getContentPane().add(sqbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, 160, -1));

        jButton1.setText("Escolher");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, -1, -1));

        buttonGroup2.add(boybutton);
        boybutton.setSelected(true);
        boybutton.setText("Boy");
        boybutton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        boybutton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        boybutton.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        boybutton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        boybutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                boybuttonMouseClicked(evt);
            }
        });
        boybutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boybuttonActionPerformed(evt);
            }
        });
        getContentPane().add(boybutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, -1, -1));

        buttonGroup2.add(girlbutton);
        girlbutton.setText("Girl");
        girlbutton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        girlbutton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        girlbutton.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        girlbutton.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        girlbutton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                girlbuttonMouseClicked(evt);
            }
        });
        getContentPane().add(girlbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, -1, -1));
        getContentPane().add(nickTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 140, -1));

        jLabel1.setText("Seu Nome:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, -1, 20));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void charbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_charbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_charbuttonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(nickTextField.getText().equals("")){
        JOptionPane.showMessageDialog(this, "Seu Nick não foi digitado");
        }else{
        
        if (bulbabutton.isSelected()) {
            p.setPoke( PokeData.getPoke(1));
        }
        else {
            if (charbutton.isSelected()) {
                p.setPoke( PokeData.getPoke(4));
            }
            else{ 
                if (sqbutton.isSelected()) {
                     p.setPoke( PokeData.getPoke(7));
                }
            }
        }
        if(boybutton.isSelected()){
        p.setCharType('b');
        }
        else{
        p.setCharType('g');
        }
        p.setId(1);
        p.setSilver(1000);
        p.addNewItem(ItemData.getItem(1));
        p.addNewItem(ItemData.getItem(1));
        p.addNewItem(ItemData.getItem(1));
        p.addNewItem(ItemData.getItem(7));
        p.addNewItem(ItemData.getItem(2));
        p.addNewItem(ItemData.getItem(3));
        p.addNewItem(ItemData.getItem(3));
        p.addNewItem(ItemData.getItem(4));
        p.addNewItem(ItemData.getItem(5));
        p.addNewItem(ItemData.getItem(5));
        p.addNewItem(ItemData.getItem(6));
        p.addNewItem(ItemData.getItem(6));
        p.addNewItem(ItemData.getItem(6));
        p.addNewItem(ItemData.getItem(6));
        p.addNewItem(ItemData.getItem(6));
        p.addNewItem(ItemData.getItem(8));
        p.setNome(nickTextField.getText());
        GameMainFrame j = new GameMainFrame(p);
        j.setVisible(true);
        this.dispose();
    }
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void boybuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boybuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boybuttonActionPerformed

    private void boybuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_boybuttonMouseClicked
    if(boybutton.getBorder()== border){
        
    }else{
    boybutton.setBorder(border);
    boybutton.setForeground(Color.white);
    girlbutton.setBorder(null);
    girlbutton.setForeground(null);
    }        // TODO add your handling code here:
    }//GEN-LAST:event_boybuttonMouseClicked

    private void girlbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_girlbuttonMouseClicked
    if(girlbutton.getBorder()== border){
        
    }else{
    girlbutton.setBorder(border);
    girlbutton.setForeground(Color.white);
    boybutton.setBorder(null);
    boybutton.setForeground(null);
    }    // TODO add your handling code here:
    }//GEN-LAST:event_girlbuttonMouseClicked

    private void bulbabuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bulbabuttonMouseClicked
    if(bulbabutton.getBorder()== border){
        
    }else{
    bulbabutton.setBorder(border);
    bulbabutton.setForeground(Color.white);
    charbutton.setBorder(null);
    charbutton.setForeground(null);
    sqbutton.setBorder(null);
    sqbutton.setForeground(null);
    }    // TODO add your handling code here:
    }//GEN-LAST:event_bulbabuttonMouseClicked

    private void charbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_charbuttonMouseClicked
    if(charbutton.getBorder()== border){
        
    }else{
    charbutton.setBorder(border);
    charbutton.setForeground(Color.white);
    bulbabutton.setBorder(null);
    bulbabutton.setForeground(null);
    sqbutton.setBorder(null);
    sqbutton.setForeground(null);
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_charbuttonMouseClicked

    private void sqbuttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sqbuttonMouseClicked
    if(sqbutton.getBorder()== border){
        
    }else{
    sqbutton.setBorder(border);
    sqbutton.setForeground(Color.white);
    charbutton.setBorder(null);
    charbutton.setForeground(null);
    bulbabutton.setBorder(null);
    bulbabutton.setForeground(null);
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_sqbuttonMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Choose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Choose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Choose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Choose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Choose().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton boybutton;
    private javax.swing.JRadioButton bulbabutton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton charbutton;
    private javax.swing.JRadioButton girlbutton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField nickTextField;
    private javax.swing.JRadioButton sqbutton;
    // End of variables declaration//GEN-END:variables
}
