/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GInterface;

import PokemonAluminum.Habilidades;
import PokemonAluminum.Pokemon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author junior
 */
public class FightFrame extends javax.swing.JFrame {

    Pokemon a, b;
    Habilidades h, h1;

    /**
     * Creates new form FightFrame
     */
    public FightFrame(Pokemon a, Pokemon b) {
        this.a = a;
        this.b = b;
        ImageIcon photoa = new ImageIcon(System.getProperty("user.dir") + "\\src\\icons\\pokegif\\00" + a.getId() + ".gif", "");
        ImageIcon photob = new ImageIcon(System.getProperty("user.dir") + "\\src\\icons\\pokegif\\00" + b.getId() + ".gif", "");
        initComponents();
        jLabel1.setIcon(photoa);
        jLabel2.setIcon(photob);
        jTextArea1.setText("");
        lifead.setValue(100);
        lifepl.setValue(100);

    }

    private FightFrame() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        plPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        adPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        lifepl = new javax.swing.JProgressBar();
        lifead = new javax.swing.JProgressBar();
        Skill1 = new javax.swing.JButton();
        Skill2 = new javax.swing.JButton();
        Skill3 = new javax.swing.JButton();
        Skill4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        plPanel.setBackground(new java.awt.Color(255, 255, 255));
        plPanel.setToolTipText("");
        plPanel.setLayout(new java.awt.BorderLayout());

        jLabel1.setBackground(new java.awt.Color(204, 204, 255));
        jLabel1.setForeground(new java.awt.Color(204, 204, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        plPanel.add(jLabel1, java.awt.BorderLayout.CENTER);

        getContentPane().add(plPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 90));

        adPanel.setBackground(new java.awt.Color(255, 255, 255));
        adPanel.setLayout(new java.awt.BorderLayout());

        jLabel2.setBackground(new java.awt.Color(204, 204, 255));
        jLabel2.setForeground(new java.awt.Color(204, 204, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        adPanel.add(jLabel2, java.awt.BorderLayout.CENTER);

        getContentPane().add(adPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 110, 90));

        jButton1.setText("Fugir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, -1, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(9, 284, 330, -1));
        getContentPane().add(lifepl, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 100, -1));
        getContentPane().add(lifead, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 100, -1));

        Skill1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Skill1ActionPerformed(evt);
            }
        });
        getContentPane().add(Skill1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 120, 20));

        Skill2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Skill2ActionPerformed(evt);
            }
        });
        getContentPane().add(Skill2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 170, 120, 20));

        Skill3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Skill3ActionPerformed(evt);
            }
        });
        getContentPane().add(Skill3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 120, 20));

        Skill4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Skill4ActionPerformed(evt);
            }
        });
        getContentPane().add(Skill4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 120, 20));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Skill1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Skill1ActionPerformed
        Skill(0);
        // TODO add your handling code here:
    }//GEN-LAST:event_Skill1ActionPerformed

    private void Skill2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Skill2ActionPerformed
        Skill(1);// TODO add your handling code here:
    }//GEN-LAST:event_Skill2ActionPerformed

    private void Skill3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Skill3ActionPerformed
        Skill(2);// TODO add your handling code here:
    }//GEN-LAST:event_Skill3ActionPerformed

    private void Skill4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Skill4ActionPerformed
        Skill(3);

// TODO add your handling code here:
    }//GEN-LAST:event_Skill4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FightFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FightFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FightFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FightFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FightFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Skill1;
    private javax.swing.JButton Skill2;
    private javax.swing.JButton Skill3;
    private javax.swing.JButton Skill4;
    private javax.swing.JPanel adPanel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JProgressBar lifead;
    private javax.swing.JProgressBar lifepl;
    private javax.swing.JPanel plPanel;
    // End of variables declaration//GEN-END:variables
public void setEvent(String s) {
        jTextArea1.setText(jTextArea1.getText() + s);
    }

    public void setHabils(String s) {
        if (Skill1.getText().equals("")) {
            Skill1.setText(s);
        } else if (Skill2.getText().equals("")) {
            Skill2.setText(s);
        } else if (Skill3.getText().equals("")) {
            Skill3.setText(s);
        } else {
            Skill4.setText(s);
        }
    }

    public void baixaLife(Pokemon a, int i) {
        if (a == this.a) {
            lifead.setValue((lifead.getValue() - i));
            
        }
        if (a == this.b) {
            lifepl.setValue(lifepl.getValue() - i);
           
        }
    }

    public void Skill(int i) {
        h.usaSkill(a.getHabilidades()[i]);
        h1.usaSkill(b.getHabilidades()[(int) (Math.random() * 3)]);
        if (a.getLife() <= 0) {
            JOptionPane.showMessageDialog(null, "Você morreu");
            a.setLose(a.getWl()[1] + 1);
            a.reset();
            b.reset();
            a.atualizaCampo();
            this.dispose();
        } else if (b.getLife() <= 0) {
            a.setNivel(a.getNivel() + 1);
            JOptionPane.showMessageDialog(null, "Você Venceu!\n Seu " + a.getNome() + " Upou! Está agora nivel " + a.getNivel());
            a.setWin(a.getWl()[0] + 1);
            a.reset();
            b.reset();
            a.atualizaCampo();
            this.dispose();
        }
    }

}
