package GInterface;



import PokemonAluminum.Habilidades;
import PokemonAluminum.PokeData;
import PokemonAluminum.Pokemon;
import java.io.File;
import javax.swing.ImageIcon;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author Igor
 */
public class Map extends javax.swing.JFrame {

    ImageIcon i,monst;
//    BackgroundMap m = new BackgroundMap();
    short n;
    File file = new File(System.getProperty("user.dir")+"\\src\\icons\\pokemons");
    boolean found;
    Pokemon a,b;
   Habilidades h;
  Habilidades h1;
  FightFrame f1;
  PokeData data = new PokeData();
    /**
     * Creates new form Map
     */
    @SuppressWarnings("empty-statement")
    public Map(BackgroundMap m) {
        initComponents();
        bg.add(m);
        headerEvento.setText("                      ");
        monsterimg.setText("                ");
        fightbutton.setVisible(false);
        leaveButton.setVisible(false);
   	i = new ImageIcon(System.getProperty("user.dir")+"\\src\\icons\\character\\down0.png", "");
        personagem.setIcon(i);
    }

    private Map() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        upButton = new javax.swing.JButton();
        leftButton = new javax.swing.JButton();
        downButton = new javax.swing.JButton();
        rightButton = new javax.swing.JButton();
        bg = new javax.swing.JPanel();
        personagem = new javax.swing.JLabel();
        eventoPanel = new javax.swing.JPanel();
        headerEvento = new javax.swing.JLabel();
        monsterimg = new javax.swing.JLabel();
        fightbutton = new javax.swing.JButton();
        leaveButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(213, 213, 253));
        setResizable(false);

        upButton.setText("▲");
        upButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upButtonActionPerformed(evt);
            }
        });

        leftButton.setText("◄ ");
        leftButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leftButtonActionPerformed(evt);
            }
        });

        downButton.setText("▼");
        downButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                downButtonActionPerformed(evt);
            }
        });

        rightButton.setText("►");
        rightButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rightButtonActionPerformed(evt);
            }
        });

        bg.setLayout(new java.awt.BorderLayout());

        personagem.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        bg.add(personagem, java.awt.BorderLayout.CENTER);

        eventoPanel.setBackground(new java.awt.Color(196, 199, 211));
        eventoPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        eventoPanel.setMinimumSize(new java.awt.Dimension(438, 85));
        eventoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        headerEvento.setText("Mensagem Oculta");
        eventoPanel.add(headerEvento, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, -1));

        monsterimg.setText("Fotinha");
        eventoPanel.add(monsterimg, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 89, 85));

        fightbutton.setText("Lutar!");
        fightbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fightbuttonActionPerformed(evt);
            }
        });
        eventoPanel.add(fightbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(284, 51, -1, -1));

        leaveButton.setText("Deixar");
        leaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leaveButtonActionPerformed(evt);
            }
        });
        eventoPanel.add(leaveButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 51, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(eventoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(leftButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(upButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(downButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(rightButton)
                .addGap(75, 75, 75))
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(upButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(downButton)
                            .addComponent(leftButton)
                            .addComponent(rightButton)))
                    .addComponent(eventoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void upButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upButtonActionPerformed

        n = (short) Math.abs(n - 1);
        i = new ImageIcon(System.getProperty("user.dir")+"\\src\\icons\\character\\up" + String.valueOf(n) + ".png", "");
        personagem.setIcon(i);
        personagem.setLocation((int) personagem.getLocation().getX(), (int) personagem.getLocation().getY() - 10);
        searchMonster();
       if(found){
               leftButton.setEnabled(false);
               rightButton.setEnabled(false);
               upButton.setEnabled(false);
               downButton.setEnabled(false);
       }
personagem.repaint();    }//GEN-LAST:event_upButtonActionPerformed

    private void downButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_downButtonActionPerformed
        // TODO add your handling code here:

        n = (short) Math.abs(n - 1);
        i = new ImageIcon(System.getProperty("user.dir")+"\\src\\icons\\character\\down"  + String.valueOf(n) + ".png", "");
        personagem.setIcon(i);
        personagem.setLocation((int) personagem.getLocation().getX(), (int) personagem.getLocation().getY() + 10);

        searchMonster();
         if(found){
               leftButton.setEnabled(false);
               rightButton.setEnabled(false);
               upButton.setEnabled(false);
               downButton.setEnabled(false);
       }

    }//GEN-LAST:event_downButtonActionPerformed

    private void leftButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leftButtonActionPerformed

        n = (short) Math.abs(n - 1);
        i = new ImageIcon(System.getProperty("user.dir")+"\\src\\icons\\character\\left" + String.valueOf(n) + ".png", "");
        personagem.setIcon(i);
        personagem.setLocation((int) personagem.getLocation().getX() - 10, (int) personagem.getLocation().getY());

        searchMonster();
        if(found){
               leftButton.setEnabled(false);
               rightButton.setEnabled(false);
               upButton.setEnabled(false);
               downButton.setEnabled(false);
       }
personagem.repaint();    }//GEN-LAST:event_leftButtonActionPerformed

    private void rightButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rightButtonActionPerformed

        n = (short) Math.abs(n - 1);
        i = new ImageIcon(System.getProperty("user.dir")+"\\src\\icons\\character\\right" + String.valueOf(n) + ".png", "");
        personagem.setIcon(i);
        personagem.setLocation((int) personagem.getLocation().getX() + 10, (int) personagem.getLocation().getY());

        searchMonster();
        if(found){
               leftButton.setEnabled(false);
               rightButton.setEnabled(false);
               upButton.setEnabled(false);
               downButton.setEnabled(false);
       }
personagem.repaint();    }//GEN-LAST:event_rightButtonActionPerformed

    private void leaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leaveButtonActionPerformed

               leftButton.setEnabled(true);
               rightButton.setEnabled(true);
               upButton.setEnabled(true);
               downButton.setEnabled(true);
              // TODO add your handling code here:
    }//GEN-LAST:event_leaveButtonActionPerformed

    private void fightbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fightbuttonActionPerformed

        f1= new FightFrame(a, b);
        h= new Habilidades(f1);
        h1= new Habilidades(f1);
        h.setAd(b);
        h.setPl(a);
        h1.setAd(a);
        h1.setPl(b);
        f1.h=h;
        f1.h1=h1;
        h.setButtonsName(a.getHabilidades());
        f1.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_fightbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Map.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Map.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Map.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Map.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Map().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton downButton;
    private javax.swing.JPanel eventoPanel;
    private javax.swing.JButton fightbutton;
    private javax.swing.JLabel headerEvento;
    private javax.swing.JButton leaveButton;
    private javax.swing.JButton leftButton;
    private javax.swing.JLabel monsterimg;
    private javax.swing.JLabel personagem;
    private javax.swing.JButton rightButton;
    private javax.swing.JButton upButton;
    // End of variables declaration//GEN-END:variables


    void searchMonster() {
        if (Math.random() > 0.85) {
            headerEvento.setText(".!:.!:.Monstro encontrado:.!.:!.");
            int count = file.listFiles().length;
            do{
            count= (int)Math.round(Math.random()*count);}
            while(count==0 || count==file.listFiles().length);
            System.out.println(file.toString()+"\\"+count+".png");
            b=data.getPoke(count);
            monst=new ImageIcon(file.toString()+"\\"+count+".png");
            monsterimg.setIcon(monst);
            fightbutton.setVisible(true);
            leaveButton.setVisible(true);
            found=true;
        }else{
            headerEvento.setText("Você não encontrou nada=/");
            monst= new ImageIcon(System.getProperty("user.dir")+"\\src\\icons\\pokemons\\0.png");
            monsterimg.setIcon(monst);
            fightbutton.setVisible(false);
            leaveButton.setVisible(false);
            found=false;
        }
     }
}
