/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GInterface;

import PokemonAluminum.Pokemon;
import java.awt.Color;
import java.awt.Container;
import java.awt.event.MouseListener;
import static javax.swing.BorderFactory.createRaisedBevelBorder;
import javax.swing.ImageIcon;

/**
 *
 * @author Igor
 */
public class MiniPokePanel extends javax.swing.JPanel {
Pokemon e;
boolean clicked=false;
    /**
     * Creates new form MiniPokePanel
     */
    public MiniPokePanel(Pokemon e) {
        this.e=e;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PokeIcon = new javax.swing.JLabel();
        PokeName = new javax.swing.JLabel();
        PokeLevel = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());
        setMaximumSize(new java.awt.Dimension(96, 134));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(96, 96));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        PokeIcon.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PokeIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pokegif/0.png"))); // NOI18N
        jPanel1.add(PokeIcon, new java.awt.GridBagConstraints());

        PokeName.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        PokeName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PokeName.setText("a");
        PokeName.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        PokeLevel.setFont(new java.awt.Font("MS Gothic", 1, 11)); // NOI18N
        PokeLevel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PokeLevel.setText("1");
        PokeLevel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(PokeName, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(PokeLevel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(8, 8, 8))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(PokeName)
                .addGap(6, 6, 6)
                .addComponent(PokeLevel))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
this.setBorder(createRaisedBevelBorder());          // TODO add your handling code here:
    }//GEN-LAST:event_formMouseEntered

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited
this.setBorder(javax.swing.BorderFactory.createEtchedBorder());
    }//GEN-LAST:event_formMouseExited

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        Container con;
        int conta=1;
        try{
    if(this.getParent().getParent().getParent().getParent().getParent().getParent().getParent() instanceof FightFrame){
FightFrame ff =(FightFrame)this.getParent().getParent().getParent().getParent().getParent().getParent().getParent();
Pokemon e1;
e1=ff.a;
ff.a=this.e;
this.e=e1;
this.setData();
ff.setHabils();
ff.setData();
//ff.atualizaPokes();
}else{
/*    conta=1;
con=this.getParent();
System.out.println(conta+" Parent(): "+con);
    while(con.getParent()!=null){
        conta+=1;
        con=con.getParent();
        System.out.println(conta+" Parent(): "+con);

}*/
 if(this.getParent().getParent().getParent().getParent().getParent().getParent() instanceof ChangeTeam){
ChangeTeam ct =(ChangeTeam)this.getParent().getParent().getParent().getParent().getParent().getParent();
ct.setPoke(this.e);
}   
 if(this.getParent().getParent().getParent().getParent().getParent().getParent().getParent().getParent() instanceof ChangeTeam){
ChangeTeam ct =(ChangeTeam)this.getParent().getParent().getParent().getParent().getParent().getParent().getParent().getParent();
ct.setPoke(this.e);
}   
    
    }
}catch(NullPointerException ex){

}        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JLabel PokeIcon;
    private javax.swing.JLabel PokeLevel;
    private javax.swing.JLabel PokeName;
    protected javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

public void setData(){
this.PokeIcon.setIcon(new ImageIcon(System.getProperty("user.dir")+"\\src\\icons\\pokegif\\"+e.getId()+".gif",""));
this.PokeName.setText(e.getNome());
this.PokeLevel.setText(String.valueOf(e.getNivel()));
if(e.getLife()<=0){
this.setDefeated();
}
}

    void setPokeUnclicked() {
        //new java.awt.Color(60,63,65));
        this.setBackground(null);
    }

    void setPokeClicked() {
        this.setBackground(Color.white);
    }
public void setDefeated(){
    MouseListener[] ms= this.getMouseListeners();
    for(MouseListener mouse : ms){
        this.removeMouseListener(mouse);
    }
    this.setBackground(Color.gray);
    this.setForeground(Color.gray);
}
}
