/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package PokemonAluminum;

/**
 *
 * @author Igor
 */
public class Choose extends javax.swing.JFrame {
Pokemon s;
PokeData data = new PokeData();
    /**
     * Creates new form Choose
     */
    public Choose() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        bulbabutton = new javax.swing.JRadioButton();
        charbutton = new javax.swing.JRadioButton();
        sqbutton = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        pidbutton = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup1.add(bulbabutton);
        bulbabutton.setText("Bulbassauro");
        bulbabutton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        bulbabutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pokemons/1.png"))); // NOI18N

        buttonGroup1.add(charbutton);
        charbutton.setText("Charmander");
        charbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pokemons/2.png"))); // NOI18N
        charbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                charbuttonActionPerformed(evt);
            }
        });

        buttonGroup1.add(sqbutton);
        sqbutton.setText("Squirtle");
        sqbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pokemons/3.png"))); // NOI18N

        jButton1.setText("Escolher");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(pidbutton);
        pidbutton.setText("Pidgey");
        pidbutton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pokemons/5.png"))); // NOI18N
        pidbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pidbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bulbabutton)
                .addGap(27, 27, 27)
                .addComponent(charbutton)
                .addGap(35, 35, 35)
                .addComponent(sqbutton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(pidbutton)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(294, 294, 294))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bulbabutton)
                    .addComponent(charbutton)
                    .addComponent(sqbutton)
                    .addComponent(pidbutton))
                .addGap(28, 28, 28)
                .addComponent(jButton1)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void charbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_charbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_charbuttonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
if(bulbabutton.isSelected()){
    System.out.println("Bulbassauro escolhido");
    s= data.getPoke(1);
}   
if(charbutton.isSelected()){
    System.out.println("Charmander escolhido");
    s=data.getPoke(2);
} 
if(sqbutton.isSelected()){
    System.out.println("Squirtle escolhido");
    s=data.getPoke(3);
}
if(pidbutton.isSelected()){
    System.out.println("Squirtle escolhido");
    s=data.getPoke(5);
}
GameMainFrame j = new GameMainFrame(s);
j.setData(s);
j.setVisible(true);
this.dispose();
// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void pidbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pidbuttonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pidbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Choose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Choose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Choose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Choose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Choose().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton bulbabutton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton charbutton;
    private javax.swing.JButton jButton1;
    private javax.swing.JRadioButton pidbutton;
    private javax.swing.JRadioButton sqbutton;
    // End of variables declaration//GEN-END:variables
}
